Repository RojoRevolution/p2_org_decider, pull requests merged in 2021-02, with the labels that each got.

#12 Models
  .gitignore
  models/idea.js
  models/org.js
  models/poll.js
  models/user.js
Labels: enhancement, good first issue

#19 Fixed issues with models
  models/idea.js
  models/org.js
  models/poll.js
  models/user.js
  package.json
Labels: bug

#42 added api routes for orgs and users
  config/config.json
  models/org.js
  models/user.js
  package.json
  routes/org-api-routes.js
  routes/user-api-routes.js
  server.js
Labels: enhancement

#46 added api routes for polls and ideas. Also created a Postman collection
  .gitignore
  collections/Yay-Nay.postman_collection.json
  config/config.json
  models/idea.js
  models/poll.js
  models/user.js
  routes/idea-api-routes.js
  routes/poll-api-routes.js
  server.js
Labels: enhancement

#49 fixed duplicates
  config/config.json
Labels: bug

#53 Bash
  db/seed.bash
  models/idea.js
  models/poll.js
  package.json
Labels: enhancement

#61 Signup org
  db/seed.bash
  routes/api-routes.js
  routes/org-api-routes.js
Labels: enhancement

#74 Catch err
  routes/api-routes.js
  routes/html-routes.js
  routes/idea-api-routes.js
  routes/org-api-routes.js
  routes/poll-api-routes.js
  routes/user-api-routes.js
Labels: Back-End, enhancement

#75 Logout Functionality
  public/js/dashboard.js
  server.js
  views/partials/dash/header.ejs
Labels: Front-End

#93 Removed Suggestions And Votes Models/Routes.
  db/schema.sql
  models/suggestions.js
  models/votes.js
  routes/suggestions-api-routes.js
  routes/votes-api-routes.js
  server.js
Labels: Back-End, enhancement

#103 Api routes
  db/seed.bash
  models/category.js
  models/idea.js
  models/poll.js
  models/user.js
  public/js/dashboard.js
  routes/api-routes.js
  routes/category-api-routes.js
  routes/html-routes.js
  routes/idea-api-routes.js
  routes/org-api-routes.js
  routes/poll-api-routes.js
  routes/user-api-routes.js
  server.js
Labels: Back-End

#104 added finder filters based on orgs for categories
  models/category.js
  models/org.js
  routes/category-api-routes.js
  routes/html-routes.js
Labels: Back-End

#112 All Cards Rendering - Need To Complete Voting Portion
  models/category.js
  models/idea.js
  public/css/main.css
  public/js/dashboard.js
  routes/html-routes.js
  routes/idea-api-routes.js
  views/category.ejs
  views/partials/dash/addNewCategory.ejs
  views/partials/dash/suggestion-block.ejs
  views/partials/dash/suggestion-cards.ejs
  views/partials/dash/vote-block.ejs
  views/partials/dash/vote-cards-active.ejs
  views/partials/dash/vote-cards.ejs
Labels: Front-End, enhancement
